## nn Approach



### Setup

In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets

import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler


from pyMLaux import plot_history, evaluate_classification_result

In [9]:
base_dir = '/home/bac/activity_prediction/implementation/'
data_dir = base_dir + 'data/'

### load & prepare dataset

the following code needs to be adapted for each protein-ligand complex individually

In [10]:
nn_data_raw_mdi = pd.read_csv(data_dir+"ACHE/ache_mdi.csv")
nn_data_raw_per = pd.read_csv(data_dir+"ACHE/ache_per.csv")
nn_data_raw = pd.read_csv(data_dir+"ACHE/ache.csv")

In [11]:
lookup = {'inactive':0,'active':1}

nn_data_per = {'data': np.array(nn_data_raw_per.iloc[:, 2:-1]),
             'target': np.array([lookup[y] for y in nn_data_raw_per.iloc[0:,-1]]),
             'feature_names': nn_data_raw_per.columns[2:-1],
             'target_names': ['inactive', 'active']}

nn_data_mdi = {'data': np.array(nn_data_raw_mdi.iloc[:, 2:-1]),
             'target': np.array([lookup[y] for y in nn_data_raw_mdi.iloc[0:,-1]]),
             'feature_names': nn_data_raw_mdi.columns[2:-1],
             'target_names': ['inactive', 'active']}

nn_data_base = {'data': np.array(nn_data_raw.iloc[:, 2:-1]),
             'target': np.array([lookup[y] for y in nn_data_raw.iloc[0:,-1]]),
             'feature_names': nn_data_raw.columns[2:-1],
             'target_names': ['inactive', 'active']}


split into train- and test-set

In [12]:
X_train_base, X_test_base, y_train_base, y_test_base = train_test_split(nn_data_base['data'], nn_data_base['target'],
                                                    test_size=0.3, random_state=4232)

X_train_mdi, X_test_mdi, y_train_mdi, y_test_mdi = train_test_split(nn_data_mdi['data'], nn_data_mdi['target'],
                                                    test_size=0.3, random_state=4232)

X_train_per, X_test_per, y_train_per, y_test_per = train_test_split(nn_data_per['data'], nn_data_per['target'],
                                                    test_size=0.3, random_state=4232)

### train and apply neural network

In [13]:
model_base = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(nn_data_base['data'].shape[1], )),
    tf.keras.layers.Dense(5, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(10, activation='softmax')
])

model_base.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model_per = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(nn_data_per['data'].shape[1], )),
    tf.keras.layers.Dense(5, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(10, activation='softmax')
])

model_per.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model_mdi = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(nn_data_mdi['data'].shape[1], )),
    tf.keras.layers.Dense(5, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(10, activation='softmax')
])

model_mdi.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])



In [14]:
history_base = model_base.fit(x=X_train_base, y=y_train_base, epochs=150, batch_size=16, validation_split=0.2, verbose=2)
history_per = model_per.fit(x=X_train_per, y=y_train_per, epochs=150, batch_size=16, validation_split=0.2, verbose=2)
history_mdi = model_mdi.fit(x=X_train_mdi, y=y_train_mdi, epochs=150, batch_size=16, validation_split=0.2, verbose=2)


Epoch 1/150


2024-04-09 19:19:28.048101: I external/local_tsl/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2024-04-09 19:19:28.559640: I external/local_xla/xla/service/service.cc:168] XLA service 0x7fa3f83222b0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-04-09 19:19:28.559685: I external/local_xla/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 3050 Laptop GPU, Compute Capability 8.6
2024-04-09 19:19:28.569982: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-04-09 19:19:28.593735: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:454] Loaded cuDNN version 8904
I0000 00:00:1712683168.664373   31051 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


36/36 - 2s - loss: 2.2234 - accuracy: 0.3405 - val_loss: 2.1252 - val_accuracy: 0.4965 - 2s/epoch - 51ms/step
Epoch 2/150
36/36 - 0s - loss: 2.0598 - accuracy: 0.5223 - val_loss: 1.9725 - val_accuracy: 0.5532 - 302ms/epoch - 8ms/step
Epoch 3/150
36/36 - 0s - loss: 1.8848 - accuracy: 0.5633 - val_loss: 1.7988 - val_accuracy: 0.5532 - 282ms/epoch - 8ms/step
Epoch 4/150
36/36 - 0s - loss: 1.7188 - accuracy: 0.5918 - val_loss: 1.6304 - val_accuracy: 0.5532 - 287ms/epoch - 8ms/step
Epoch 5/150
36/36 - 0s - loss: 1.5984 - accuracy: 0.5651 - val_loss: 1.4800 - val_accuracy: 0.5532 - 257ms/epoch - 7ms/step
Epoch 6/150
36/36 - 0s - loss: 1.4264 - accuracy: 0.5882 - val_loss: 1.3046 - val_accuracy: 0.5603 - 253ms/epoch - 7ms/step
Epoch 7/150
36/36 - 0s - loss: 1.2827 - accuracy: 0.6025 - val_loss: 1.0723 - val_accuracy: 0.6099 - 256ms/epoch - 7ms/step
Epoch 8/150
36/36 - 0s - loss: 1.0579 - accuracy: 0.6631 - val_loss: 0.8544 - val_accuracy: 0.6950 - 261ms/epoch - 7ms/step
Epoch 9/150
36/36 - 0s

Evaluate Testdata using model

In [16]:

pred_base = model_base.predict(X_test_base)
pred_per = model_per.predict(X_test_per)
pred_mdi = model_mdi.predict(X_test_mdi)

print("---------Base-Prediction----------")
evaluate_classification_result(y_test_base,pred_base,classes=nn_data_base["target_names"])
print("---------Permutation-FeatureSelection-Prediction----------")
evaluate_classification_result(y_test_per,pred_per,classes=nn_data_per["target_names"])
print("---------MDI-FeatureSelection-Prediction----------")
evaluate_classification_result(y_test_mdi,pred_mdi,classes=nn_data_mdi["target_names"])


10/10 [==============================] - 0s 5ms/step
---------Base-Prediction----------
[[ 96  41]
 [ 29 135]]


Class inactive:
    Sensitivity (TPR):  70.073% (96 of 137)
    Specificity (TNR):  82.317% (135 of 164)
    Precision:          76.800% (96 of 125)
    Neg. pred. value:   76.705% (135 of 176)
Class active:
    Sensitivity (TPR):  82.317% (135 of 164)
    Specificity (TNR):  70.073% (96 of 137)
    Precision:          76.705% (135 of 176)
    Neg. pred. value:   76.800% (96 of 125)

Overall accuracy:   76.744% (231 of 301)
Balanced accuracy:  76.195%
---------Permutation-FeatureSelection-Prediction----------
[[ 93  44]
 [ 30 134]]


Class inactive:
    Sensitivity (TPR):  67.883% (93 of 137)
    Specificity (TNR):  81.707% (134 of 164)
    Precision:          75.610% (93 of 123)
    Neg. pred. value:   75.281% (134 of 178)
Class active:
    Sensitivity (TPR):  81.707% (134 of 164)
    Specificity (TNR):  67.883% (93 of 137)
    Precision:          75.281% (134 of 178)
    N

array([[ 87,  50],
       [ 30, 134]])